apiVersion: v1
kind: ReplicationController

metadata:
  name: myapp
  labels:
    name: app
    app: front-end

spec:
  template:

    metadata:
      name: app-prod
      labels:
        app: myapp
        type: front-end

    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2

